{
    "fix": "https://github.com/python/cpython/commit/0ae8579b85f9b0cd3f287082ad6e194bdb025d88",
    "verify": "0",
    "localId": 69276,
    "project": "cpython3",
    "fuzzer": "libfuzzer",
    "sanitizer": "msan",
    "crash_type": "Use-of-uninitialized-value",
    "severity": "Medium",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1716800393,
                "content": "Detailed Report: https://oss-fuzz.com/testcase?key=5548877519323136\n\nProject: cpython3\nFuzzing Engine: libFuzzer\nFuzz Target: fuzz_pycompile\nJob Type: libfuzzer_msan_cpython3\nPlatform Id: linux\n\nCrash Type: Use-of-uninitialized-value\nCrash Address: \nCrash State:\n  get_localsplus_counts\n  _PyCode_Validate\n  _PyAssemble_MakeCodeObject\n  \nSanitizer: memory (MSAN)\n\nRecommended Security Severity: Medium\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_msan_cpython3&range=202402070607:202402080600\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=5548877519323136\n\nIssue filed automatically.\n\nSee https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1716816123,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Disclosure-2024-08-26"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "1083371212",
                    "displayName": "am...@ammaraskar.com"
                },
                "timestamp": 1716910955,
                "content": "Reported as https://github.com/python/cpython/issues/119666"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1717499166,
                "amendments": [
                    {
                        "fieldName": "Cc",
                        "newOrDeltaValue": "g...@krypto.org pablo...@python.org s...@python.org"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1718098069,
                "content": "ClusterFuzz testcase 5548877519323136 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_msan_cpython3&range=202406090600:202406100601\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 69276,
                "sequenceNum": 5,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1718111434,
                "content": "This bug has been fixed. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "0ae8579b85f9b0cd3f287082ad6e194bdb025d88",
    "repo_addr": "https://github.com/python/cpython.git"
}